[project]
title = "Student Habits & Performance Analysis"
version = "0.1.0"
port = 8501
slug = "student-habits-383607"  
entrypoint = "hello.py"    

[branding]
name = "Student Habits Analytics"
logo = "./images/student.jpg"
favicon = "./images/student_favicon.ico"
primaryColor = "#2980b9"

[data.sample_csv]
type = "csv"
path = "data/sample.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"